import "./App.css";
import React from "./react"
import './componentscomparametro'
import './index.css'
import './Primeiro'
import '/.Index.js'
import './Card'
import '.Card.css'

import App from "../App";


export default function App(props){
   <div classname ='Card'>
  
  ReactDOM.render(
      <p>]"test</p>
      <div>{tag}
<title>
"ola react"
</title>
</div>,  
</div>
Document.getelementbyid ("root")
     
        
    
           }
    


  

    
       
       
    




          

      